### ISSUE TITLE
build DNS-325 fail

### ISSUE THREAD

**Issue by gpancot** [awanga/alt-f-next#1]
Hi,

alt-f_dns325_defconfig master release fail with:

___ DNS-325-rev-Ax ___
Image Name:   Alt-F-1.0.1-next, kernel 4.19.13
Created:      Fri Aug 14 19:21:29 2020
Image Type:   ARM Linux Kernel Image (uncompressed)
Data Size:    1807505 Bytes = 1765.14 KiB = 1.72 MiB
Load Address: 00008000
Entry Point:  00008000

mkfw: Firmware creation FAILED at rootfs too big by 446528 bytes, max is 3145728, exiting.
Makefile:824: recipe for target 'target-post-image' failed

**Comment by awanga** [comment]
This was due to the sqsplit configuration being broken with the changes and updates to packages. There are some patches in the dev branch (specifically [7a1794a](https://github.com/awanga/alt-f-next/commit/7a1794a25e6ed9932f334cce0691a21828c49b0a) and [0d25ad9](https://github.com/awanga/alt-f-next/commit/0d25ad986d366a87ce4e3a10766247bb064a9621)) that should fix this issue. Will merge into master once I do some more alpha testing on my DNS-323.

**Comment by gpancot** [comment]
version 2020.05.1 (beta) build ok.
thanks.
