### ISSUE TITLE
CIFS/SMB/SMBv1/SMBv2/SMBv3/Samba

### ISSUE THREAD

**Issue by Neustradamus** [awanga/alt-f-next#10]
@awanga: Have you seen this project, and repos?
- https://github.com/cifsd-team
- https://github.com/cifsd-team/ksmbd
- https://github.com/cifsd-team/ksmbd-tools

I think it is better to use it, no?

**Comment by awanga** [comment]
Thanks for the link! I've spent way to much time coaxing Samba 4 to (mostly) work, so this looks like a much better solution (and likely small enough to fit in the base firmware again). I'll see if I can test it out when I get a chance.

**Comment by Black6spdZ** [comment]
the performance improvements look VERY promising!.. would breath new life into these old NAS boxes

**Comment by Neustradamus** [comment]
@awanga: Any news on it?
Soon one year of my ticket...

**Comment by Neustradamus** [comment]
@awanga: Have you seen my previous comment?

**Comment by awanga** [comment]
Not much time to work on this post-pandemic, but I did poke at it. Seems promising, but kernel support is likely the issue. It moves code that otherwise would be in userspace (initrd and HDD) into the kernel - and there's not much room for newer kernel versions, much less additional features in the flash of the aging DNS hardware. Probably not worth the hassle for this system, unfortunately.

**Comment by Neustradamus** [comment]
@awanga: Any news on it?

**Comment by Neustradamus** [comment]
For information: Recent Linux on the D-Link DNS-313
(Last boot 2024-05-15 on kernel v6.6.30 with OpenWRT as rootfs)
- https://www.df.lth.se/~triad/krad/dlink-dns-313/
