### ISSUE TITLE
missing uuidgen & other e2fsprogs files

### ISSUE THREAD

**Issue by gpancot** [awanga/alt-f-next#3]
missing uuidgen needed for httpd and other e2fsprogs:

$ diff -u board/dns32x/ipkgfiles/e2fsprogs.lst-org board/dns32x/ipkgfiles/e2fsprogs.lst
--- board/dns32x/ipkgfiles/e2fsprogs.lst-org    2020-09-15 10:45:16.472083000 +0200
+++ board/dns32x/ipkgfiles/e2fsprogs.lst        2020-09-15 09:12:35.956083000 +0200
@@ -25,12 +25,16 @@
 ./usr/lib/libext2fs.so
 ./usr/lib/libext2fs.so.2
 ./usr/lib/libext2fs.so.2.4
+./usr/lib/libuuid.so
+./usr/lib/libuuid.so.1
+./usr/lib/libuuid.so.1.2
 ./usr/lib/libss.so
 ./usr/lib/libss.so.2
 ./usr/lib/libss.so.2.0
 ./usr/sbin/badblocks
 ./usr/sbin/dumpe2fs
 ./usr/sbin/e2freefrag
+./usr/bin/uuidgen
 ./usr/sbin/e2fsck
 ./usr/sbin/e2scrub
 ./usr/sbin/e2scrub_all
@@ -47,5 +51,6 @@
 ./usr/share/et/et_c.awk
 ./usr/share/et/et_h.awk
 ./usr/share/ss
+./usr/sbin/uuidd
 ./usr/share/ss/ct_c.awk
 ./usr/share/ss/ct_c.sed

**Comment by awanga** [comment]
Actually, I think these files are in the util-linux package (see cce269e). fsck and the other filesystem progs appear to be working for me in the latest master.

Having said that, there were some commits that might affect operations on filesystems that haven't made it into master yet -- specifically fixes for mdev and hot.sh that were causing some issues detecting and mounting partitions (75301df), and the busybox version of blkid was running instead of the util-linux version which actually seems to work the way we want it to (c64fc29).
